// // <auto-generated/>
//
// using System.Collections.Immutable;
// using StackExchange.Redis;
//
// namespace R8.RedisMapper.ConsoleSample;
//
// public partial class UserCacheModel : IRedisCacheObjectAdapter<UserCacheModel>
// {
//     ImmutableArray<string> IRedisCacheObjectAdapter<UserCacheModel>.Properties =>
//         new ImmutableArray<string>
//         {
//             nameof(UserCacheModel.UserId),
//             nameof(UserCacheModel.Username),
//             nameof(UserCacheModel.CreatedAt), 
//             nameof(UserCacheModel.IsAdmin), 
//         };
//
//     bool IRedisCacheObjectAdapter<UserCacheModel>.SetValue(UserCacheModel instance, string propertyName, RedisValue value)
//     {
//         switch (propertyName)
//         {
//             case nameof(UserCacheModel.UserId):
//             {
//                 instance.UserId = (int) value;
//                 break;
//             }
//             case nameof(UserCacheModel.Username):
//             {
//                 instance.Username = (string) value;
//                 break;
//             }
//             case nameof(UserCacheModel.CreatedAt):
//             {
//                 instance.CreatedAt = DateTimeValueFormatter.Instance.Read<System.DateTime>(value);
//                 break;
//             }
//             case nameof(UserCacheModel.IsAdmin):
//             {
//                 instance.IsAdmin = (bool) value;
//                 break;
//             }
//             default:
//                 return false;
//         }
//
//         return true;
//     }
//
//     RedisValue IRedisCacheObjectAdapter<UserCacheModel>.GetValue(UserCacheModel instance, string propertyName)
//     {
//         return propertyName switch
//         {
//             nameof(UserCacheModel.UserId) => (RedisValue) instance.UserId,
//             nameof(UserCacheModel.Username) => (RedisValue) instance.Username,
//             nameof(UserCacheModel.CreatedAt) => (RedisValue) DateTimeValueFormatter.Instance.Write(instance.CreatedAt),
//             nameof(UserCacheModel.IsAdmin) => (RedisValue) instance.IsAdmin,
//             _ => default
//         };
//     }
// }